const WEEKS = [
    { week: 1,  size: 'Not yet visible', size_mm: 0,   emoji: '✨', baby: "Fertilisation hasn't happened yet.", object: "Tiny Sparkle" },
    { week: 2,  size: 'Microscopic',     size_mm: 0,   emoji: '🔬', baby: "Ovulation and conception happen.", object: "Microscopic Cell" },
    { week: 3,  size: 'Pin head',        size_mm: 0.1, emoji: '📌', baby: "Implantation begins.", object: "Tip of a Needle" },
    { week: 4,  size: 'Poppy seed',      size_mm: 1,   emoji: '🌺', baby: "Neural tube begins forming.", object: "Sugar Grain" },
    { week: 5,  size: 'Sesame seed',     size_mm: 2,   emoji: '🌻', baby: "The heart begins to beat!", object: "MicroSD Card Chip" },
    { week: 6,  size: 'Sweet pea',       size_mm: 5,   emoji: '🫘', baby: "Tiny buds appear.", object: "Pencil Eraser" },
    { week: 7,  size: 'Blueberry',       size_mm: 8,   emoji: '🫐', baby: "Brain grows rapidly.", object: "Coffee Bean" },
    { week: 8,  size: 'Raspberry',       size_mm: 15,  emoji: '🍒', baby: "Major organs forming.", object: "Standard Penny" },
    { week: 9,  size: 'Grape',           size_mm: 20,  emoji: '🟣', baby: "Muscles connect.", object: "Thimble" },
    { week: 10, size: 'Strawberry',      size_mm: 30,  emoji: '🍓', baby: "Critical development complete.", object: "Lego Brick (2x2)" },
    { week: 11, size: 'Lime',            size_mm: 40,  emoji: '🍋', baby: "Baby can hiccup.", object: "Ping Pong Ball (approx)" },
    { week: 12, size: 'Plum',            size_mm: 55,  emoji: '🍑', baby: "Kicking and flexing.", object: "Small Chicken Egg" },
    { week: 13, size: 'Peach',           size_mm: 70,  emoji: '🍑', baby: "Fingerprints forming.", object: "Golf Ball" },
    { week: 14, size: 'Lemon',           size_mm: 85,  emoji: '🍋', baby: "Sucking movements.", object: "Tennis Ball (approx)" },
    { week: 15, size: 'Apple',           size_mm: 100, emoji: '🍎', baby: "Baby can hear.", object: "Standard Lightbulb" },
    { week: 16, size: 'Avocado',         size_mm: 115, emoji: '🥑', baby: "Head holds up.", object: "Computer Mouse" },
    { week: 17, size: 'Pear',            size_mm: 130, emoji: '🍐', baby: "Fat accumulating.", object: "iPhone 13 Mini (approx)" },
    { week: 18, size: 'Bell pepper',     size_mm: 140, emoji: '🫑', baby: "Yawns and stretches.", object: "Rubik's Cube" },
    { week: 19, size: 'Mango',           size_mm: 150, emoji: '🥭', baby: "Sensory development.", object: "Soda Can (12oz)" },
    { week: 20, size: 'Banana',          size_mm: 160, emoji: '🍌', baby: "Halfway there!", object: "Paperback Book" },
    { week: 21, size: 'Carrot',          size_mm: 265, emoji: '🥕', baby: "Pattern of movement.", object: "Standard TV Remote" },
    { week: 22, size: 'Papaya',          size_mm: 275, emoji: '🍈', baby: "Eyebrows appeared.", object: "Football (American)" },
    { week: 23, size: 'Grapefruit',      size_mm: 285, emoji: '🍊', baby: "Sleeping cycle.", object: "Basketball (Youth)" },
    { week: 24, size: 'Corn',            size_mm: 295, emoji: '🌽', baby: "Baby is viable.", object: "1L Water Bottle" },
    { week: 25, size: 'Rutabaga',        size_mm: 340, emoji: '🥔', baby: "Responds to touch.", object: "2L Milk Carton" },
    { week: 26, size: 'Lettuce head',    size_mm: 355, emoji: '🥬', baby: "Eyes open.", object: "Bowling Ball (approx)" },
    { week: 27, size: 'Cauliflower',     size_mm: 370, emoji: '🥦', baby: "3rd Trimester begins.", object: "Standard Pillow" },
    { week: 28, size: 'Eggplant',        size_mm: 375, emoji: '🍆', baby: "Eyes detect light.", object: "Desktop Keyboard" },
    { week: 29, size: 'Squash',          size_mm: 385, emoji: '🥒', baby: "Lungs maturing.", object: "Laptop (13 inch)" },
    { week: 30, size: 'Cabbage',         size_mm: 395, emoji: '🟢', baby: "Regulate temp.", object: "Laptop (15 inch)" },
    { week: 31, size: 'Coconut',         size_mm: 405, emoji: '🥥', baby: "Turn its head.", object: "Electric Kettle" },
    { week: 32, size: 'Squash',          size_mm: 420, emoji: '🍈', baby: "Brain development.", object: "Microwave Oven" },
    { week: 33, size: 'Pineapple',       size_mm: 430, emoji: '🍍', baby: "Skull hardening.", object: "Standard Bed Pillow" },
    { week: 34, size: 'Cantaloupe',      size_mm: 450, emoji: '🍈', baby: "Fingerprints formed.", object: "Carry-on Suitcase" },
    { week: 35, size: 'Honeydew',        size_mm: 460, emoji: '🍈', baby: "Kidneys working.", object: "Standard Microwave" },
    { week: 36, size: 'Romaine',         size_mm: 470, emoji: '🌿', baby: "Sucking muscles.", object: "Gym Duffel Bag" },
    { week: 37, size: 'Greens',          size_mm: 480, emoji: '🌱', baby: "Full term!", object: "Standard Bed Pillow" },
    { week: 38, size: 'Leek',            size_mm: 490, emoji: '🪴', baby: "Gaining fat.", object: "Full-sized Keyboard" },
    { week: 39, size: 'Watermelon',      size_mm: 500, emoji: '🍉', baby: "Ready to meet.", object: "Standard Watermelon" },
    { week: 40, size: 'Pumpkin',         size_mm: 510, emoji: '🌕', baby: "Due date!", object: "Small Suitcase" },
    { week: 41, size: 'Pumpkin',         size_mm: 515, emoji: '🎃', baby: "Induction offered.", object: "Large Beach Ball" },
    { week: 42, size: 'Pumpkin',         size_mm: 520, emoji: '🎃', baby: "Post-term.", object: "Large Suitcase" }
];
